### ISSUE TITLE
Defaults with ||

### ISSUE THREAD

**Issue by eldoy** [eldoy/weblang#10]
Would be cool to be able to set defaults with double pipe:

```yml
hello: $user.name || no name
```

Right now you have to do:
```yml
$name: $user.name
if:
  $name:
     is: undefined
then:
  $name: no name
hello: $name
```
