### ISSUE TITLE
Extension can't get vars automatically

### ISSUE THREAD

**Issue by eldoy** [eldoy/weblang#2]
```yml
$values:
    name: Tester
    email: test@7i.no
    password: testtest
    confirm: testtest
api:
  action: message/create
  values: $values
```

This doesn't work automatically for extensions. Fix?
