### ISSUE TITLE
String concatenation with pipes

### ISSUE THREAD

**Issue by eldoy** [eldoy/weblang#21]
Could it be feasible to have string concatenation with pipes?

```yml
$item: |
  Project: ${title | trim}

@map$projects: $item
```

Would it be possible to just use mustache for this?

```yml
$item: |
  Project: {{title | trim}}
```

Check out https://github.com/jvitela/mustache-wax, seems to do it. Should we then just pass in the state as data to mustache?
