### ISSUE TITLE
Use @ or % or ? or ('') after setting for something

### ISSUE THREAD

**Issue by eldoy** [eldoy/weblang#22]
Need this kind of syntax, if we have:
`api('user/create', { query: 1 })`

how to model that with weblang?

```
@api?user/create:
  query: 1
```

**Comment by eldoy** [comment]
Use

```yml
=result@api:
  path: user/create
  params:
    query: 1
```
